### ISSUE TITLE
Arxiu editar

### ISSUE THREAD

**Issue by lcastienc** [joeldiazcc/DAW_M07_S7_Practica5#4]

**Comment by lcastienc** [comment]
Subida y actualizacion del archivo para editar productos de la bbdd

**Comment by ipetrov20** [comment]
CREATE TABLE ddbb(
id int NOT NULL AUTO_INCREMENT,
name varchar(50),
description varchar(50),
price varchar(50),
q_sold int,
PRIMARY KEY(id)
);
